live_config_reload = true

import: [~/.config/alacritty/tokyonight-night.toml]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 20.0

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Medium"

[cursor]
style= "Beam"
