source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=#ebbcba,bg=default'
set -g pane-border-style 'fg=#6e6a86,bg=default'
set -g message-style 'fg=#e0def4,bg=#26233a'
set -g mode-style 'fg=#191724,bg=#ebbcba'
set -g status-style 'fg=#e0def4,bg=default'
set -g status-left-length 40
set -g status-right-length 120
set -g status-left "#[fg=#191724,bg=#31748f,bold] #S #[fg=#31748f,bg=default] "
set -g status-right "#[fg=#9ccfd8]#{b:pane_current_path} #[fg=#ebbcba]%H:%M "
set -g window-status-separator " "
setw -g window-status-format "#[fg=#908caa,bg=default] #I:#W "
setw -g window-status-current-format "#[fg=#191724,bg=#ebbcba,bold] #I:#W#{?window_zoomed_flag,(),} "

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color '#ebbcba'
set -g @floax-text-color '#9ccfd8'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

run '~/.config/tmux/plugins/tpm/tpm'
